version: 0.2

phases:
  pre_build:
    commands:
      - echo Loggin to amazon ECR
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050323630.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=975050323630.dkr.ecr.us-east-1.amazonaws.com/varsha-spring-boot-hello
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build Started on `date`
      - echo create jar file
      - mvn clean install
      - echo building docker images
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo build completed on `date`
      - echo pushing to repo
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definition file
      # Give container name
      - DOCKER_CONTAINER_NAME=spring-hello-ecr
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
      - echo "Deploying ECS CloudFormation stack..."
      - aws cloudformation deploy --template-file ecs-farget-cluster.yml --stack-name varsha-hello-ecs --capabilities CAPABILITY_NAMED_IAM
      - echo "Deployment complete!"
